version: '3.1'

services:
  tcp-server:
    env_file:
      - ./dockerfiles/tcp-server/.env
    build:
      context: ../
      dockerfile: ./tools/dockerfiles/tcp-server/Dockerfile
    ports:
      - "8080:8080"
    
  prometheus:
    build:
      context: ../
      dockerfile: ./tools/dockerfiles/prometheus/Dockerfile
    ports:
      - "9090:9090"